package io.github.camilyed.tlsh;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/** Creates repeatable binary inputs shared by tests that must run without external fixtures. */
final class DeterministicTestInput {

  private DeterministicTestInput() {}

  /**
   * Generates the same varied byte sequence for every invocation with the same size.
   *
   * <p>The input is intentionally generated from a fixed initial state and the requested size. It
   * is not random test data: changing the algorithm changes compatibility digests and must
   * therefore be an explicit decision. The xorshift calculation is only a compact way to create
   * many local byte patterns; it is not suitable for cryptography.
   *
   * @param size number of bytes to generate
   * @return new deterministic byte array of the requested size
   */
  static byte[] bytes(final int size) {
    final byte[] input = new byte[size];
    int state = 0x6D2B79F5 ^ size;
    for (int index = 0; index < input.length; index++) {
      state ^= state << 13;
      state ^= state >>> 17;
      state ^= state << 5;
      input[index] = (byte) state;
    }
    return input;
  }

  /**
   * Writes a repeatable generated input to a test-owned path.
   *
   * @param path destination path, normally located in a JUnit temporary directory
   * @param size number of bytes to generate and write
   * @return the supplied destination path
   * @throws IOException when the generated bytes cannot be written
   */
  static Path write(final Path path, final int size) throws IOException {
    return Files.write(path, bytes(size));
  }
}
